### ISSUE TITLE
Problemas de Compatibilidade do Jersey por dependencias desnecessárias

### ISSUE THREAD

**Issue by melanke** [pagarme/pagarme-java#80]
Boa tarde,

A partir do momento que declarei essa dependência do pagarme no pom.xml meu servidor Jersey parou de funcionar.

Verifiquei que vocês possuem uma outra versão do Jersey no pom.xml de vocês, deve ser esse o motivo, mas por eu ter umas configurações específicas não posso trocar a minha versão.

Para solucionar o problema copiei todo o código Java de vocês para o meu próprio projeto, e funcionou como uma luva, a única dependência que tive que adicionar foi o evo-inflector:1.2.1

Por tanto acho que vocês poderiam remover as outras dependências.

Grato :)

**Comment by melanke** [comment]
Na verdade consegui corrigir excluindo as dependencias, mas de qualquer maneira, não vi necessidade de vocês incluírem...

```
<dependency>
      <groupId>me.pagar</groupId>
      <artifactId>pagarme-java</artifactId>
      <version>1.5.0</version>
      <exclusions>
        <exclusion>
          <groupId>org.glassfish.jersey.core</groupId>
          <artifactId>jersey-client</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.ws.rs</groupId>
          <artifactId>jsr311-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by henriquekano** [comment]
Olá, @melanke!

Realmente a lib possui algumas dependências que, de acordo com o tempo, se tornaram dependências não necessárias que não foram removidas :/.
O que acha de nos ajudar com um PR? :)

**Comment by pedrohenriqueveiga** [comment]
Olá Pessoal, venho aqui ressuscitar este post e informar, que tive um problema relacionado.

Ao fazer um deploy na AWS, quando é feito a requisição, é disparado uma exceção.
onde o erro é 
`me.pagar.model.PagarMeException: java.lang.ClassNotFoundException: com.sun.ws.rs.ext.RuntimeDelegateImpl
	at me.pagar.model.PagarMeException.buildWithError(PagarMeException.java:21) ~[pagarme-java-2.1.2.jar:na]
	at me.pagar.model.RestClient.<init>(RestClient.java:143) ~[pagarme-java-2.1.2.jar:na]
	at me.pagar.model.PagarMeRequest.execute(PagarMeRequest.java:40) ~[pagarme-java-2.1.2.jar:na]
	at me.pagar.model.PagarMeModel.save(PagarMeModel.java:191) ~[pagarme-java-2.1.2.jar:na]
	at me.pagar.model.Card.save(Card.java:142) ~[pagarme-java-2.1.2.jar:na]`

A princípio achei que era a dependência do Jersey, porém era a do Javax.
Assim fiz a exclusão do `javax.ws.rs`e resolveu os problemas.
Seria interessante revisar isso e atualizar inclusive o maven para que a galera..
Valeu @melanke
